name: CD Pipeline
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Update and install dependencies
            sudo apt-get update -y
            sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common

            # Install Docker
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            sudo apt-get update -y
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io

            # Add the SSH user to the Docker group
            sudo usermod -aG docker ${{ secrets.SSH_USERNAME }}

            # Install Docker Compose
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose

            # Navigate to the project directory and deploy
            cd /home/ubuntu/
            if [ ! -d "fastapi-book-project" ]; then
              git clone https://github.com/goodddybag/fastapi-book-project
            fi
            cd fastapi-book-project/
            git pull
            docker-compose up -d --build

            # Wait for containers to start
            sleep 10

            # Test if the API is running correctly
            RESPONSE_CODE=$(curl -o /dev/null -s -w "%{http_code}\n" http://35.175.175.118/api/v1/books/1)
            if [ "$RESPONSE_CODE" -ne 200 ]; then
              echo "ERROR: API returned $RESPONSE_CODE instead of 200"
              exit 1
            else
              echo "API is running correctly"
            fi
           
